name: Netlify Production Deployment
on:
  push:
    branches:
      - main
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci
      - name: Install netlify CLI
        run: npm install netlify-cli -g
      - name: Deploy Production
        run: netlify deploy --build -a ${{secrets.NETLIFY_TOKEN}} --site ${{secrets.SITE_ID}} --prod
