name: 'Netlify Preview Deploy'

on:
  pull_request:
    types: ['opened', 'edited', 'synchronize']

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci
      - run: npm run test
  deploy-preview:
    name: 'Deploy Preview'
    runs-on: ubuntu-latest
    outputs:
      preview-url: ${{ steps.deploy-preview.outputs.preview-url }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci
      - name: Install netlify CLI
        run: npm install netlify-cli -g
      - name: Install jq
        run: sudo apt-get install jq
      - name: Deploy preview
        id: deploy-preview  # Added this line
        run: |
          DEPLOYMENT_URL=$(netlify deploy --build -a ${{secrets.NETLIFY_TOKEN}} --site ${{secrets.SITE_ID}} --json | jq -r '.deploy_url')
          echo "preview-url=$DEPLOYMENT_URL" >> $GITHUB_OUTPUT
  e2e:
    runs-on: ubuntu-latest
    needs: deploy-preview
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
        env:
          PLAYWRIGHT_TEST_BASE_URL: ${{ needs.deploy-preview.outputs.preview-url }}

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
